### ISSUE TITLE
Exception lors de la création des indexes de recherche du MongoDB v7+

### ISSUE THREAD

**Issue by vincentlambert** [Eurelis/Eurelis-KB-Framework#11]
Exception remontée depuis la MongoDBVectorStoreFactory sur l'appel `collection.create_search_index(search_index)` :

```python
pymongo.errors.OperationFailure: command not found, full error: {'ok': 0, 'errmsg': 'command not found', 'code': 59, 'codeName': 'CommandNotFound'}
```

**Comment by vincentlambert** [comment]
Mise en place d'un Quick-Fix en attente de traitement de fond.

**Comment by jeromediaz** [comment]
Au final le problème n'est pas uniquement lié à une version de mongodb, mais aussi à une implémentation qui est incomplète sur les instances mutualisées
mise en place d'un try except, affichage dans les logs de la configuration d'index attendue
