### ISSUE TITLE
La configuration embeddings.cache_folder ne supporte pas les template strings

### ISSUE THREAD

**Issue by vincentlambert** [Eurelis/Eurelis-KB-Framework#5]

**Comment by jeromediaz** [comment]
@vincentlambert je n'ai pas reproduis de problèmes au niveau de la configuration embeddings.cache_folder, à ce niveau là les template strings sont bien supportés
=> mauvais format fournit dans la configuration ?

J'ai trouvé néanmoins un endroit où le support des TS n'était pas bon,
au niveau de la création de chemin automatique pour le record_manager 
=> erreur de diagnostic sur le problème réel ?

**Comment by jeromediaz** [comment]
Problème trouvé et corrigé au niveau de l'output du dataset où effectivement la variable folder ne passait pas par le système de résolution
