### ISSUE TITLE
Output dans la console

### ISSUE THREAD

**Issue by vincentlambert** [Eurelis/Eurelis-KB-Framework#7]
Lors d'une recherche de similarités, il y a un gros output dans la console.
```python
factory = LangchainWrapperFactory()
factory.set_config_path("config/kbf/knowledge_base.json")
wrapper = factory.build(None)
results = wrapper.search_documents(query, include_relevance=True)
```
A supprimer si dans lib KBF.

Entre :
`2024-02-08 10:24:44,506 - eurelis_kb_framework.langchain_wrapper INFO [START] Performing similarity search`
et
`2024-02-08 10:24:45,947 - eurelis_kb_framework.langchain_wrapper INFO [END] Performing similarity search`

**Comment by jeromediaz** [comment]
J'ai regardé en mode pas à pas, tous les warnings viennent de langchain
