### ISSUE TITLE
Indexation d'un dataset depuis une sitemap.xml en https présentant un certificat non valide

### ISSUE THREAD

**Issue by vincentlambert** [Eurelis/Eurelis-KB-Framework#8]
Il n'est pas possible d'indexer un site depuis une sitemap si le certificat n'est pas valide.
Peut-on désactiver cette vérification ?

Pour reproduire :
- Dépôt site Eurelis
- `gmake run-local` lance le site sur [https://local.eurelis.com:8080/](https://local.eurelis.com:8080/)
- `gmake kbf-index-dev` lève une exception `SSLCertVerificationError`

**Comment by jeromediaz** [comment]
Au niveau du loader, il n'y a pas de variables prévues côté langchain pour désactiver la vérification

Si je me base sur https://stackoverflow.com/a/77756711/2119709

utiliser les variables d'environnmenet
REQUESTS_CA_BUNDLE=""
CURL_CA_BUNDLE=""

pourrait désactiver côté python la vérification

**Comment by vincentlambert** [comment]
Je n'ai pas réussi à faire fonctionner la solution proposée.
