### ISSUE TITLE
Erreur en utilisant le loader : "url"

### ISSUE THREAD

**Issue by NicolasLoisyEurelis** [Eurelis/Eurelis-KB-Framework#9]
J'ai une erreur quand j'utilise le loader "url".

Configuration knowledge_base.json :
```
"id": "url",
"loader": {
    "provider": "url",
    "url": "https://fr.wikipedia.org/wiki/Alan_Turing",
    "recursive": false
}, 
```

ERREUR :
```
File "C:\Users\Nicolas\Desktop\WORKSPACE\KBF_TestProject\.venv\Lib\site-packages\eurelis_kb_framework\document_loaders\url\__init__.py", line 80, in build
    return RecursiveUrlLoader(self.url, **self.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: RecursiveUrlLoader.__init__() got an unexpected keyword argument 'provider'
```

Dans la ligne 81 du fichier `Eurelis-KB-Framework\src\eurelis_kb_framework\document_loaders\url\__init__.py` :
`return RecursiveUrlLoader(self.url, **self.params)`

Observation : 
La présence de "provider" dans "loader" est obligatoire. "provider" est passé dans **self.params du construct RecursiveUrlLoader, mais ce dernier n'en veut pas.

Solution temporaire : 
Dans la ligne : `return RecursiveUrlLoader(self.url, **self.params)`
Supprimer le 2e paramètre : `return RecursiveUrlLoader(self.url)`

**Comment by jeromediaz** [comment]
Le correctif ne passe pas par la suppression des paramètres de type keyword, sinon on pert la configuration sur la récursivité, mais par l'utilisation de la version filtrée des params

**Comment by jeromediaz** [comment]
pour note,

remplacement de 

`return RecursiveUrlLoader(self.url, **self.params) `

par

        
```
parameters = self.get_optional_params()

return RecursiveUrlLoader(self.url, **parameters)
```


la méthode get_optional_params() se base sur la liste des OPTIONAL_PARAMS définis au niveau d'une factory pour récupérer un sous-dictionnaire de parameters ne contenant que certaines clefs,

cela permet de définir des paramètres qu'on peut passer "tel quel" entre la configuration json et la classe langchain utilisée en dessous
